language: python
dist: xenial
cache: pip
sudo: required
python:
  - 3.7
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - ./tests/scripts/unit_tests.sh
  # - ./manage.py test rules -- FIX OR REMOVE THIS
  # - ./manage.py test classifier -- FIX OR REMOVE THIS
  - sphinx-build -W docs/source docs/build
  # - ./tests/scripts/pylint.sh -- FIX THIS
  - bandit --ini setup.cfg -r .
after_success:
  coveralls
